#dataset_root: /media/cv3/store1/postgraduate/y2023/WLF/datasets/CSL-Daily/frames_256x256/256
dataset_root: /media/cv3/store1/postgraduate/y2023/WLF/datasets/Csl_adv/PGD/0.1
dict_path: ./preprocess/CSL-Daily/gloss_dict.npy
evaluation_dir: ./evaluation/slr_eval
evaluation_prefix: CSL-Daily-groundtruth
